### ISSUE TITLE
[FEAT] 채팅 뷰 기능 다듬기

### ISSUE THREAD

**Issue by KimSeongGyu1** [woowacourse-teams/2020-devbie#187]
## 목적 및 필요성
- 채팅 뷰의 기능적 개선이 몇 가지 필요하다

## 작업 상세 내용
- [x] Connection 시 별명을 가져온다
- [ ] 채팅방 참여 인원 수를 가져온다
- [x] Disconnect를  x 버튼을 이용해서 처리한다
- [x] 채팅 리스트가 최신의 내용을 보여주도록 한다

**Comment by ghost** [comment]
채팅방 인원 가져오기
disconnect

이건 추가되면 좋을 것 같아요!

**Comment by KimSeongGyu1** [comment]
넵
disconnect는 워딩을 정확히 안써서 확인 못하셨나 보네요
단어 수정할게요
